### ISSUE TITLE
Morning session: Peer-to-peer code review ♻

### ISSUE THREAD

**Issue by abenezer-addisu** [uno36/Awesome-Books#4]
Hi Tite lunda🖐
I'm Abenezer your morning session partner

**Good job so far!** 🎉
<img src="https://media4.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

But there are some issues that you still need to work on but you are almost there!

Highlights
✔Good job overall following the template design ✅
✔Correct GitHub Flow ✅

Something Changes ♻️

- [ ] Fix margin property

![image](https://user-images.githubusercontent.com/105231513/235607256-6c5314bc-6ec2-4e17-953a-da28c96b1da8.png)

Please try to mimic the figma design for a better layout.

Cheers and Happy coding!👏👏👏

**Comment by TiteLunda** [comment]
Thanks so much
